ARXIV_CATEGORIES = [
    "Artificial Intelligence",
    "Computation and Language",
    "Computer Vision and Pattern Recognition",
    "Machine Learning",
    "Robotics",
    "Information Retrieval",
    "Neural and Evolutionary Computing",
    "Cryptography and Security",
    "Software Engineering",
    "Operating Systems",
    "Networking and Internet Architecture",
    "Human-Computer Interaction",
    "Computational Geometry",
    "Quantum Physics",
    "Statistics",
    "Optimization and Control",
    "Probability",
    "Applied Physics",
    "Data Analysis, Statistics and Probability",
    "Medical Physics",
    "Optics",
    "Bioinformatics",
    "Genomics",
    "Quantitative Methods",
    "Economics",
    "Signal Processing",
    "Systems and Control",
]
